version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  db:
    image: postgres
    environment:
      POSTGRES_DB: titanicdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
